<?php

/**
 * @file
 * Role Expire module
 *
 * Enables user roles to expire on given time.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Form\FormStateInterface;

/*******************************************************************************
 * API functions
 ******************************************************************************/

/**
 * API function; Get expiration time of a user role.
 * @param $uid
 *   User ID.
 * @param $rid
 *   Role ID.
 * @return
 *  Array with the expiration time.
 */
function role_expire_get_user_role_expiry_time($uid, $rid) {

  $query = Database::getConnection()->select('role_expire', 'n');
  $query->fields('n', array('expiry_timestamp'));
  $query->condition('n.uid', $uid, '=');
  $query->condition('n.rid', $rid, '=');
  $result = $query->execute()->fetchField();

  return (!empty($result)) ? $result : '';
}

/**
 * API function; Get expiration of all roles of a user.
 * @param $uid
 *   User ID.
 * @return
 *  Array with the expiration time.
 */
function role_expire_get_all_user_records($uid) {

  $query = Database::getConnection()->select('role_expire', 'n');
  $query->fields('n', array(
      'rid',
      'expiry_timestamp',
    )
  );
  $query->condition('n.uid', $uid, '=');
  $result = $query->execute()->fetchAll();

  $return = array();
  foreach ($result as $row) {
    $return[$row->rid] = $row->expiry_timestamp;
  }

  return $return;
}

/**
 * API function; Delete a record from the database.
 *
 * @param $uid
 *   User ID.
 * @param $rid
 *   Role ID.
 * @return
 */
function role_expire_delete_record($uid, $rid) {
  $query = Database::getConnection()->delete('role_expire');
  $query->condition('uid', $uid)->condition('rid', $rid);
  $query->execute();
}

/**
 * API function; Delete all records for role.
 *
 * @param $rid
 *   Role ID.
 * @return
 */
function role_expire_delete_role_records($rid) {
  Database::getConnection()->delete('role_expire')->condition('rid', $rid)->execute();
}

/**
 * API function; Delete all user expirations.
 *
 * @param $uid
 *   User ID.
 * @return
 */
function role_expire_delete_user_records($uid) {
  Database::getConnection()->delete('role_expire')->condition('uid', $uid)->execute();
}

/**
 * API function; Insert or update a record in the database.
 *
 * @param $uid
 *   User ID.
 * @param $rid
 *   Role ID.
 * @param $expiry_time
 *   The expiration timestamp.
 */
function role_expire_write_record($uid, $rid, $expiry_timestamp) {

  // Delete previous expiry for user and role if it exists.
  role_expire_delete_record($uid, $rid);

  // Insert new expiry for user and role.
  $query = Database::getConnection()->insert('role_expire');
  $query->fields(array('uid', 'rid', 'expiry_timestamp'));
  $query->values(array('uid' => $uid, 'rid' => $rid, 'expiry_timestamp' => $expiry_timestamp));
  $query->execute();
}

/**
 * API function; Get the default duration for a role.
 *
 * @param $rid
 *   Required. The role_id to check.
 *
 * @return
 *  Int storing the default duration days of the role or an empty string if not set.
 */
function role_expire_get_default_duration($rid) {

  $query = Database::getConnection()->select('role_expire_length', 'n');
  $query->fields('n', array('duration'));
  $query->condition('n.rid', $rid, '=');
  $result = $query->execute()->fetchField();

  return (!empty($result)) ? $result : '';
}

/**
 * API function; Insert or update the default expiry duration for a role.
 *
 * @param $rid
 *   Role ID.
 * @param $duration
 *   The duration integer (days).
 */
function role_expire_set_default_duration($rid, $duration) {

  if (isset($duration) && is_numeric($duration) && $duration > 0) {
    // Delete previous default duration if it exists.
    role_expire_delete_default_duration($rid);

    // Insert new default duration.
    $query = Database::getConnection()->insert('role_expire_length')->fields(array('rid', 'duration'));
    $query->values(array('rid' => $rid, 'duration' => $duration));
    $query->execute();
  }
}

/**
 * API function; Delete default duration(s) for a role.
 *
 * @param $rid
 *   Required. The role_id to remove.
 */
function role_expire_delete_default_duration($rid) {
  Database::getConnection()->delete('role_expire_length')->condition('rid', $rid)->execute();
}

/**
 * API function; Get all records that should be expired.
 *
 * @param $time
 *   Optional. The time to check, if not set it will check current time.
 */
function role_expire_get_expired($time = '') {
  $return = array();
  if (!$time) {
    date_default_timezone_set(drupal_get_user_timezone());
    $time = \Drupal::time()->getRequestTime();
  }

  $query = Database::getConnection()->select('role_expire', 'n');
  $query->fields('n', array(
      'rid',
      'uid',
      'expiry_timestamp',
    )
  );
  $query->condition('n.expiry_timestamp', $time, '<=');
  $result = $query->execute()->fetchAll();

  foreach ($result as $row) {
    $return[] = $row;
  }
  return $return;
}

/**
 * API function; Get roles to assign on expiration (global configuration).
 *
 * @return array
 *   Returns an array where the key is the original rid and the value the
 *   one that has to be assigned on expiration. The array will be empty if
 *   configuration is not set.
 */
function role_expire_get_roles_after_expiration() {
  $config =  \Drupal::config('role_expire.config');
  $values_raw = $config->get('role_expire_default_roles');
  $values = empty($values_raw) ? array() : json_decode($values_raw, TRUE);
  return $values;
}

/*******************************************************************************
 * Hook implementations
 ******************************************************************************/

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add role expiration fields to user register/edit forms.
 */
function role_expire_form_user_form_alter(&$form, FormStateInterface $form_state) {
  $current_path = \Drupal::service('path.current')->getPath();
  $path_args = explode('/', $current_path);

  $account_id = is_numeric($path_args[2]) ? $path_args[2] : NULL;

  if (!empty($account_id)) {
    // User edit form.
    $account = \Drupal\user\Entity\User::load($account_id);
  }
  else {
    // User register form.
    $account = NULL;
  }

  $form = array_merge_recursive($form, role_expire_add_expiration_input($account));
  $form['#validate'][] = 'role_expire_user_form_submit_validate';
  $form['actions']['submit']['#submit'][] = 'role_expire_user_form_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add role default duration field to role edit form.
 */
function role_expire_form_user_role_form_alter(&$form, FormStateInterface $form_state) {
  $form['role_expire'] = array(
    '#title' => t("Default duration for the role %role",
      array('%role' => ucfirst($form['label']['#default_value']))),
    '#type' => 'textfield',
    '#size' => 8,
    '#default_value' => role_expire_get_default_duration($form['id']['#default_value']),
    '#maxlength' => 5,
    '#attributes' => array('class' => array('role-expire-role-expiry')),
    '#description' => t("Default number of days this role should be active. Leave blank for no limit.")
  );
  $form['#validate'][] = 'role_expire_user_admin_role_validate';
  $form['actions']['submit']['#submit'][] = 'role_expire_user_admin_role_submit';
  $form['actions']['delete']['#submit'][] = 'role_expire_user_admin_role_submit_delete';
}

/**
 * Form validation handler invoked by role_expire_form_user_admin_role_alter.
 *
 * Ensures that default duration is integer >= 0.
 */
function role_expire_user_admin_role_validate($form, FormStateInterface &$form_state) {
  $values = $form_state->getValues();

  if (isset($values['role_expire']) && strlen($values['role_expire'])) {
    $default_duration = $values['role_expire'];
    if (!is_numeric($default_duration)) {
      $form_state->setErrorByName('role_expire', 'Default role expiry must be numeric');
    }
    elseif ($default_duration < 0) {
      $form_state->setErrorByName('role_expire', 'Default role expiry must be greater than or equal to zero days.');
    }
  }
}

/**
 * Form submit handler invoked by role_expire_form_user_admin_role_alter.
 *
 * Updates default duration in database.
 */
function role_expire_user_admin_role_submit($form, FormStateInterface &$form_state) {
  $values = $form_state->getValues();

  // If the form doesn't specify a default duration, then delete default duration.
  // Otherwise, set the default duration to what's specified.
  $new_default_duration = $values['role_expire'];
  if (is_numeric($new_default_duration) && $new_default_duration > 0) {
    role_expire_set_default_duration($values['id'], $values['role_expire']);
    drupal_set_message('New default role expiration set.');
  }
  else {
    role_expire_delete_default_duration($values['id']);
  }
}

/**
 * Form delete handler invoked by role_expire_form_user_admin_role_alter.
 *
 * Removes default duration in database.
 */
function role_expire_user_admin_role_submit_delete($form, FormStateInterface &$form_state) {
  $values = $form_state->getValues();

  role_expire_delete_default_duration($values['id']);
}

/**
 * Form validation handler invoked by user_register_form and user_form alter hooks.
 *
 * Allows to get and save the current roles of the user before the new user data is
 * actually saved. By doing this, in the submit method we can ensure role expire data
 * consistency.
 *
 * https://drupal.stackexchange.com/questions/200620/insert-a-value-to-form-state
 */
function role_expire_user_form_submit_validate($form, FormStateInterface &$form_state) {
  $account = $form_state->getFormObject()->getEntity();
  $original_roles = $account->getRoles();
  $form_state->set('original_roles', $original_roles);
}

/**
 * Form submit handler invoked by user_register_form and user_form alter hooks.
 *
 * TODO: This method needs debugging.
 *
 * On D7 version, this code was inside hook_user_update. Updates default duration in database.
 */
function role_expire_user_form_submit($form, FormStateInterface &$form_state) {
  $values = $form_state->getValues();
  $account = $form_state->getFormObject()->getEntity();
  $original_roles = $form_state->get('original_roles');

  if ((\Drupal::currentUser()->hasPermission('administer role expire') || \Drupal::currentUser()->hasPermission('administer users'))) {

    // Add roles expiry information for the user role.
    foreach ($values as $key => $value) {
      if (strpos($key, 'role_expire_') === 0) {
        $rid = substr($key, strlen('role_expire_'));
        if ($value != '' && in_array($rid, $values['roles'])) {
          $expiry_timestamp = strtotime($value);
          role_expire_write_record($account->id(), $rid, $expiry_timestamp);
        }
        else {
          role_expire_delete_record($account->id(), $rid);
        }
      }
    }

    if (isset($values['roles'])) {

      // Add default expiration to any new roles that have been given to the user.
      $new_roles = array_diff($values['roles'], $original_roles);
      if (isset($new_roles)) {
        // We have the new roles, loop over them and see whether we need to assign expiry to them.
        foreach ($new_roles as $role_id) {
          role_expire_process_default_role_duration_for_user($role_id, $account->id());
        }
      }

      // Remove expiration for roles that have been removed from the user.
      $del_roles = array_diff($original_roles, $values['roles']);
      if (isset($del_roles)) {
        // We have the deleted roles, loop over them and remove their expiry info.
        foreach ($del_roles as $role_id) {
          role_expire_delete_record($account->id(), $role_id);
        }
      }

    } // if values[roles]

  } // if permissions

}

/**
 * Implements hook_user_insert().
 */
function role_expire_user_insert($account) {

  if ((\Drupal::currentUser()->hasPermission('administer role expire') || \Drupal::currentUser()->hasPermission('administer users'))) {

    // This adds default expiration to any new roles that have been given to the user.
    $new_roles = $account->getRoles();
    // We have the new roles, loop over them and see whether we need to assign expiry to them.
    foreach ($new_roles as $role_id) {
      role_expire_process_default_role_duration_for_user($role_id, $account->id());
    }
  }
}

/**
 * Implements hook_user_cancel().
 */
function role_expire_user_cancel($edit, $account, $method) {
  // Delete user records.
  role_expire_delete_user_records($account->id());
}

/**
 * Implements hook_user_delete().
 */
function role_expire_user_delete($account) {
  // Delete user records.
  role_expire_delete_user_records($account->id());
}

/**
 * Implements hook_user_load().
 */
function role_expire_user_load($users) {
  // We don't load the information to the user object. Other modules can use
  // our API to query the information.

  /**
   * Load the starter roles into a static cache so it is easy to
   * see what has changed later on.
   */
  foreach ($users as $account) {
    _role_static_user_roles($account->id(), $account->getRoles());
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 *
 * This new hook replaces D7 hook_user_view.
 */
function role_expire_user_view(&$build, $entity, $display, $view_mode) {
  $account = $build['#user'];
  $currentUser = \Drupal::currentUser();

  if ($currentUser->hasPermission('administer role expire') || $currentUser->hasPermission('administer users') || $currentUser->id() == $account->id()) {

    // 1. Gather all role expiration information.
    $roles = array();
    $expiry_roles = role_expire_get_all_user_records($account->id());
    foreach (($account->getRoles()) as $rid) {
      if (array_key_exists($rid, $expiry_roles)) {
        $roles[] =  t("%role role expiration date: %timedate", array('%role' => ucfirst($rid), '%timedate' => \Drupal::service('date.formatter')->format($expiry_roles[$rid])));
      }
    }

    // 2. Print all role expiration information.
    if ($roles) {

      $render_array = array(
        '#theme' => 'item_list',
        '#items' => $roles,
        '#title' => t('Role expiration'),
        '#attributes' => array('class' => array('role-expiry-roles')),
        '#weight' => 1000,
      );
      $build['role_expire'] = $render_array;
    }
  }
}

/**
 * Implements hook_cron().
 *
 * TODO: This method needs intensive debugging.
 */
function role_expire_cron() {
  if ($expires = role_expire_get_expired()) {
    $roles = _role_expire_get_role();
    foreach ($expires as $expire) {

      // Remove the role expiration record from the role_expires table.
      role_expire_delete_record($expire->uid, $expire->rid);

      // Remove the role from the user.
      $account = \Drupal\user\Entity\User::load($expire->uid);

      // If the account *does* exist, update it.
      if (!empty($account)) {

        // Assign a new role after expiration if requested given configuration.
        $new_roles = role_expire_get_roles_after_expiration();
        if (!empty($new_roles) && !empty($new_roles[$expire->rid])) {
          $new_rid = $new_roles[$expire->rid];
          $account->addRole($new_rid);
          // TODO: Maybe here we should assign a default expiration for this new role if its available.
          //role_expire_process_default_role_duration_for_user($new_rid, $account->id());
          \Drupal::logger('role_expire')->notice(t('Added role @role to user @account.', array('@role' => $new_rid, '@account' => $account->id())));
        }

        $account->removeRole($expire->rid);
        $account->save();

        \Drupal::logger('role_expire')->notice(t('Removed role @role from user @account.', array('@role' => $expire->rid, '@account' => $account->id())));
      }
      else {

        // The account doesn't exist. Throw a warning message.
        \Drupal::logger('role_expire')->notice(t('Data integrity warning: Role_expire table updated, but no user with uid @uid.', array('@uid' => $expire->uid)));
      }
    }
  }
}


/**
 * Add form element that accepts the role expiration time.
 *
 * @param User $account
 *   Edited user or null.
 *
 * @return
 *   Form element.
 */
function role_expire_add_expiration_input($account) {
  $form = array();

  if (\Drupal::currentUser()->hasPermission('administer users') || \Drupal::currentUser()->hasPermission('administer role expire')) {

    $form['#attached']['library'][] = 'role_expire/role_expire';
    $form['roles']['#attributes'] = array('class' => array('role-expire-roles'));

    foreach (_role_expire_get_role() as $rid => $role) {
      if (!is_null($account)) {
        $expiry_timestamp = role_expire_get_user_role_expiry_time($account->id(), $rid);
      }
      else {
        $expiry_timestamp = '';
      }

      $form['role_expire_' . $rid] = array(
        '#title' => t("%role role expiration time", array('%role' => $role)),
        '#type' => 'textfield',
        '#default_value' => !empty($expiry_timestamp) ? date("Y-m-d H:i:s", $expiry_timestamp) : '',
        '#attributes' => array('class' => array('role-expire-role-expiry')),
        '#description' => t("Leave blank for default role expiry (never, or the duration you have set for the role), enter date and time in format: <em>yyyy-mm-dd hh:mm:ss</em> or use relative time i.e. 1 day, 2 months, 1 year, 3 years.")
      );
    }

    $form['#validate'][] = '_role_expire_validate_role_expires';
  }

  return $form;
}

/*******************************************************************************
 * Helper functions
 ******************************************************************************/

/**
 * Helper function; Store user roles for this page request.
 *
 * @return
 *   array of roles
 */
function _role_static_user_roles($id, $roles = '') {
  static $user_roles = array();

  if (!isset($user_roles[$id]) && is_array($roles)) {
    $user_roles[$id] = $roles;
  }
  if (!isset($user_roles[$id])) {
    return FALSE;
  }
  else {
    return $user_roles[$id];
  }

}

/**
 * Helper function; Get valid roles.
 *
 * @return array
 */
function _role_expire_get_role() {
  $roles_out = array();
  $roles = user_roles(TRUE);
  unset($roles[Drupal\Core\Session\AccountInterface::AUTHENTICATED_ROLE]);

  // Return in the same format as in D7 version to simplify D8 upgrade.
  foreach ($roles as $label => $role) {
    $roles_out[$role->id()] = $role->label();
  }
  return $roles_out;
}

/**
 * Form validation handler for the role expiration on the user_profile_form().
 *
 * @see user_profile_form()
 */
function _role_expire_validate_role_expires(&$form, FormStateInterface &$form_state) {

  $values = $form_state->getValues();
  date_default_timezone_set(drupal_get_user_timezone());
  $time = \Drupal::time()->getRequestTime();

  foreach ($values as $name => $value) {
    if (strpos($name, 'role_expire_') === 0 && trim($value) != '') {
      $expiry_time = strtotime($value);
      if (!$expiry_time) {
        $form_state->setErrorByName($name, t("Role expiry is not in correct format."));
      }
      if ($expiry_time <= $time) {
        $form_state->setErrorByName($name, t("Role expiry must be in the future."));
      }
    }
  }
}

/**
 * Sets the default role duration for the current user/role combination.
 *
 * @param $role_id
 *   The ID of the role.
 * @param $uid
 *   The user ID.
 */
function role_expire_process_default_role_duration_for_user($role_id, $uid) {
  // Does a default expiry exist for this role?
  $role_day_period = role_expire_get_default_duration($role_id);
  if ($role_day_period) {
    // Is there already an expiry for this user and role?
    $user_role_expiry = role_expire_get_user_role_expiry_time($uid, $role_id);
    // If the expiry is empty then we act!.
    if (!$user_role_expiry) {
      // Add the current date to the role day period and save it back to the role_expire row.
      role_expire_write_record($uid, $role_id, mktime(0, 0, 0, date("m"), date("d") + $role_day_period, date("Y")));
    }
  }
}
